### PR TITLE
Improve the input fields so that they don't emit <div></div>

### PR DESCRIPTION
**Pull request by ditorodev**
## Description
Introduced `<Input/>` component which is flexible and is kinda the same of `<ContentEditable/>` with the only difference that it works over a `<textarea>` element which is better for text sanitization. Also it introduces a Regexp based filter at a component level which enables the dev to remove selected types of text unicode(such as` \s, \t, \n`, just an example you can filter whatever you want).

## Requirements

- [x] Can adapt to whatever layout it is placed in
- [ ] Is flexible: grows with its text-content. (Note: this kinda works, still i have to figure out a way to do the proper calculations of size so it does not bugout, if too much text is placed the algorithm starts adding extra lines of text)

PS:  The way this components expands is simple. It just calculates how many characters('a' <--- a character) can be placed inside the current input width based on the current font size, then it just does a division to know how many lines the current text should take(its just an estimation, thats why there is problems. Maybe someone who knows maths better than me can figure this out haha; im sure it is not that complicated anyways ill still look at way to do this)

@mattpocock @ezhikov (I'm tagging you guys bc maybe you'll know better)

### CODE REVIEW

**Comment by ezhikov** [comment]
Not sure about intended final result here, since it clashes a bit with #6 in terms of styling. For resizing inputs I really like this solution: https://codepen.io/shshaw/pen/c72208b279d750f1ab46b6a45bbd04d7

**Comment by mattpocock** [comment]
@ditorojuan Don't have time to look at fixes for this today, does @ezhikov's suggestion look feasible?

FYI - you can probably keep the description fields as they are. Since it doesn't matter if they contain HTML, we can keep the nice experience of the react-contenteditable.

I've added two things on master that'll help this PR. I've added some husky hooks to run prettier on commit - that should help enforce code style. Second, I've added a script to to get sextant to target localStorage instead of the file system - `yarn fe start:demo` - that should mean it's a little less annoying to have to prune database.json when you commit.

**Comment by ditorojuan** [comment]
> Not sure about intended final result here, since it clashes a bit with #6 in terms of styling. For resizing inputs I really like this solution: https://codepen.io/shshaw/pen/c72208b279d750f1ab46b6a45bbd04d7

I like this approach, will try this later this week. ATM this PR solves the problem of sanitizing the inputs only problem is the stylo which I think I can fix with this CSS trick

**Comment by ditorojuan** [comment]
Well I tried the CSS approach and a new approach which was basically letting the browser calculate the size of the height with a shadow component, but still im getting weird sizes this time when the input is of length 0. 

@mattpocock I would suggest to just use same react-contenteditable but this time sanitize the input before sending it out to the events, it could be on a wrapper.

**Pull request closed without merging**
