### PR TITLE
style applied to "Duplicate" button

### PR DESCRIPTION
**Pull request by mwarger**

### CODE REVIEW

**Comment by mwarger** [comment]
Fixes #26

**Comment by mattpocock** [comment]
@mwarger I like this. It doesn't fit with the other buttons, but that's because the other buttons are rubbish. I'll keep this unmerged for now until I get some time, then I'll make the other buttons look like this.

**Comment by mwarger** [comment]
> @mwarger I like this. It doesn't fit with the other buttons, but that's because the other buttons are rubbish. I'll keep this unmerged for now until I get some time, then I'll make the other buttons look like this.

@mattpocock I think it looked clean, and kind of matched the aesthetic (but I am not a designer 😛 ).  I can also take a look at abstracting a button component to use for the other buttons.  Let me know if you want help with this.

**Comment by mwarger** [comment]
@mattpocock Please review when you're able.  Small changes with this.

**Pull request closed without merging**
